# -*- coding: utf-8 -*-
"""Copy of Final_Year_Project_Spectrograms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YT9scrtehQNGXGwgCQ9mOJdxrZJzk19O
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import librosa
import librosa.display
import numpy as np
import matplotlib.pyplot as plt

# Main output folder for spectrograms
OUTPUT_BASE = '/content/drive/MyDrive/STFT_Spectrograms'

# Create base folder
if not os.path.exists(OUTPUT_BASE):
    os.makedirs(OUTPUT_BASE)

desired_length = 30  # seconds

def preprocess_audio(file_path, desired_length):
    audio, sr = librosa.load(file_path, sr=None)

    if len(audio) > desired_length * sr:
        audio = audio[:desired_length * sr]
    else:
        audio = np.pad(audio, (0, desired_length * sr - len(audio)))

    return audio, sr

def plot_and_save_stft(audio, sr, save_path):
    window_size_sec = 0.025
    n_fft = int(sr * window_size_sec)
    hop_length = n_fft  # no overlap

    # STFT magnitude
    stft = np.abs(librosa.stft(audio, n_fft=n_fft, hop_length=hop_length))

    # Convert to dB
    stft_db = librosa.amplitude_to_db(stft, ref=np.max)

    # Plot
    plt.figure(figsize=(6, 4))
    librosa.display.specshow(
        stft_db,
        sr=sr,
        hop_length=hop_length,
        x_axis='time',
        y_axis=None,
        cmap='inferno'
    )
    plt.axis('off')
    plt.tight_layout()

    # Save
    plt.savefig(save_path, bbox_inches='tight', pad_inches=0)
    plt.close()

DATASET_PATH = '/content/drive/MyDrive/Music-Samples'

instrument_folders = {
    'Flute': 'Flute',
    'Mridangam': 'Mridangam',
    'Nadaswaram': 'Nadaswaram',
    'Shehnai': 'Shehnai',
    'Thavil': 'Thavil',
    'Santoor': 'Santoor',
    'Veena': 'Veena',
    'Violin': 'Violin'
}

for instrument in instrument_folders:
    folder_path = os.path.join(OUTPUT_BASE, instrument)
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)

for instrument, folder_name in instrument_folders.items():

    audio_folder = os.path.join(DATASET_PATH, folder_name)
    output_folder = os.path.join(OUTPUT_BASE, instrument)

    print(f"Processing {instrument}...")

    for file_name in os.listdir(audio_folder):
        if file_name.endswith('.wav'):
            file_path = os.path.join(audio_folder, file_name)

            audio, sr = preprocess_audio(file_path, desired_length)

            save_path = os.path.join(
                output_folder,
                file_name.replace('.wav', '.png')
            )

            plot_and_save_stft(audio, sr, save_path)