# -*- coding: utf-8 -*-
"""Copy of Final_Year_Project_MFCC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MtmP-Bx7_aLA1cFYQvOss6jrVocz67ND

#First Phase - I(Extraction of MFCC)

##DataSet Loading and Preprocessing of Audio
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import re
import librosa
import librosa.display
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

DATASET_PATH = "/content/drive/MyDrive/Music-Samples"

# List instrument folders
instrument_folders = os.listdir(DATASET_PATH)

print("Instrument folders found:")
for folder in instrument_folders:
    print(folder)

desired_length = 30

def preprocess_audio(file_path, desired_length):
    audio, sr = librosa.load(file_path, sr=None)

    # Remove silence
    audio, _ = librosa.effects.trim(audio, top_db=20)

    # Normalize amplitude
    audio = librosa.util.normalize(audio)

    # Cut or pad to desired length
    if len(audio) > desired_length * sr:
        audio = audio[:desired_length * sr]
    else:
        audio = np.pad(audio, (0, max(0, desired_length * sr - len(audio))), 'constant')

    return audio, sr

"""##MFCC Extraction for Flute"""

# Correct path to Flute folder
audio_folder_flute = '/content/drive/MyDrive/Music-Samples/Flute'

# Function to extract numbers from file names
def sort_key(filename):
    match = re.search(r'\d+', filename)
    return int(match.group()) if match else float('inf')

# List and sort files numerically
audio_files_flute = sorted(os.listdir(audio_folder_flute), key=sort_key)

# Display the sorted audio files
print(audio_files_flute)

# Step 3: Extract MFCC features
def extract_mfcc(audio, sr, n_mfcc=13):
    window_size_sec = 0.025
    n_fft = int(sr * window_size_sec)
    mfccs = librosa.feature.mfcc(y=audio, sr=sr, n_fft=n_fft, hop_length=int(n_fft), n_mfcc=n_mfcc)
    return mfccs

def plot_waveform(audio, sr, title):
    plt.figure(figsize=(6, 2))  # Smaller size for the plot (width=6, height=2)
    librosa.display.waveshow(audio, sr=sr)
    plt.title(f'Waveform of {title}', fontsize=10)
    plt.xlabel('Time (s)', fontsize=8)
    plt.ylabel('Amplitude', fontsize=8)
    plt.tight_layout()
    plt.show()

file_path_check = os.path.join(audio_folder_flute, 'Flute1.wav')
file_path_check

# Prepare a DataFrame to store the MFCCs
mfcc_features_flute = []

# Iterate through each file in the folder
for file_name in audio_files_flute:
    if file_name.endswith('.wav'):
        file_path = os.path.join(audio_folder_flute, file_name)
        # Call preprocess_audio to load the audio and get the sample rate
        audio, sr = preprocess_audio(file_path, desired_length)
         # Display the waveform of the current audio file
        plot_waveform(audio, sr, file_name)

        mfcc_flute = extract_mfcc(audio,sr)
         # Append a tuple of (MFCC features, label)
        mfcc_features_flute.append((mfcc_flute, 'Flute'))

# Prepare a list to store the MFCC features and labels
mfcc_data_flute = []
# Store each MFCC array and its label in the list
for mfcc_array_flute, label in mfcc_features_flute:
    mfcc_data_flute.append({'features': mfcc_array_flute, 'label': label})
# Convert to a DataFrame
mfcc_df_flute = pd.DataFrame(mfcc_data_flute)

mfcc_df_flute

mfcc_df_flute['features'][0].shape

# Flattening the features and storing them in a new DataFrame
flattened_features_flute = []
labels_flute = []

for index, row in mfcc_df_flute.iterrows():
    # The features are already a numpy array, so no need to load with json.loads
    feature_array = row['features'].flatten()
    flattened_features_flute.append(feature_array)
    labels_flute.append(row['label'])
# Create a new DataFrame
flattened_df_flute = pd.DataFrame(flattened_features_flute)
flattened_df_flute['label'] = labels_flute

# Display the new DataFrame
flattened_df_flute

# Save the MFCC features to a CSV file (optional)
flattened_df_flute.to_csv('/content/drive/MyDrive/mfcc_features_flute.csv', index=False)

print("MFCC features extracted and saved.")

"""##MFCC Extraction for Mridangam"""

# Correct path to mridangam folder
audio_folder_mridangam = '/content/drive/MyDrive/Music-Samples/Mridangam'
# Function to extract numbers from file names
def sort_key(filename):
    match = re.search(r'\d+', filename)
    return int(match.group()) if match else float('inf')

# List and sort files numerically
audio_files_mridangam = sorted(os.listdir(audio_folder_mridangam), key=sort_key)

# Display the sorted audio files
print(audio_files_mridangam)

# Prepare a DataFrame to store the MFCCs
mfcc_features_mridangam = []

# Iterate through each file in the folder
for file_name in audio_files_mridangam:
    if file_name.endswith('.wav'):
        file_path = os.path.join(audio_folder_mridangam, file_name)
        # Call preprocess_audio to load the audio and get the sample rate
        audio, sr = preprocess_audio(file_path, desired_length)

        mfcc_mridangam = extract_mfcc(audio,sr)
         # Append a tuple of (MFCC features, label)
        mfcc_features_mridangam.append((mfcc_mridangam, 'Mridangam'))

# Prepare a list to store the MFCC features and labels
mfcc_data_mridangam = []
# Store each MFCC array and its label in the list
for mfcc_array_mridangam, label in mfcc_features_mridangam:
    mfcc_data_mridangam.append({'features': mfcc_array_mridangam, 'label': label})
# Convert to a DataFrame
mfcc_df_mridangam = pd.DataFrame(mfcc_data_mridangam)

# Flattening the features and storing them in a new DataFrame
flattened_features_mridangam = []
labels_mridangam = []

for index, row in mfcc_df_mridangam.iterrows():
    # The features are already a numpy array, so no need to load with json.loads
    feature_array_mridangam = row['features'].flatten()
    flattened_features_mridangam.append(feature_array_mridangam)
    labels_mridangam.append(row['label'])
# Create a new DataFrame
flattened_df_mridangam = pd.DataFrame(flattened_features_mridangam)
flattened_df_mridangam['label'] = labels_mridangam

# Display the new DataFrame
flattened_df_mridangam.shape

# Save the MFCC features to a CSV file (optional)
flattened_df_mridangam.to_csv('/content/drive/MyDrive/mfcc_features_mridangam.csv', index=False)

print("MFCC features extracted and saved.")

"""##MFCC Extraction for Nadaswaram"""

# Correct path to nadaswaram folder
audio_folder_nadaswaram = '/content/drive/MyDrive/Music-Samples/Nadaswaram'
# Function to extract numbers from file names
def sort_key(filename):
    match = re.search(r'\d+', filename)
    return int(match.group()) if match else float('inf')

# List and sort files numerically
audio_files_nadaswaram = sorted(os.listdir(audio_folder_nadaswaram), key=sort_key)

# Display the sorted audio files
print(audio_files_nadaswaram)

# Prepare a DataFrame to store the MFCCs
mfcc_features_nadaswaram = []

# Iterate through each file in the folder
for file_name in audio_files_nadaswaram:
    if file_name.endswith('.wav'):
        file_path = os.path.join(audio_folder_nadaswaram, file_name)
        # Call preprocess_audio to load the audio and get the sample rate
        audio, sr = preprocess_audio(file_path, desired_length)

        mfcc_nadaswaram = extract_mfcc(audio,sr)
         # Append a tuple of (MFCC features, label)
        mfcc_features_nadaswaram.append((mfcc_nadaswaram, 'Nadaswaram'))

# Prepare a list to store the MFCC features and labels
mfcc_data_nadaswaram = []
# Store each MFCC array and its label in the list
for mfcc_array_nadaswaram, label in mfcc_features_nadaswaram:
    mfcc_data_nadaswaram.append({'features': mfcc_array_nadaswaram, 'label': label})
# Convert to a DataFrame
mfcc_df_nadaswaram = pd.DataFrame(mfcc_data_nadaswaram)

# Flattening the features and storing them in a new DataFrame
flattened_features_nadaswaram = []
labels_nadaswaram = []

for index, row in mfcc_df_nadaswaram.iterrows():
    # The features are already a numpy array, so no need to load with json.loads
    feature_array_nadaswaram = row['features'].flatten()
    flattened_features_nadaswaram.append(feature_array_nadaswaram)
    labels_nadaswaram.append(row['label'])

# Create a new DataFrame
flattened_df_nadaswaram = pd.DataFrame(flattened_features_nadaswaram)
flattened_df_nadaswaram['label'] = labels_nadaswaram

# Display the new DataFrame
flattened_df_nadaswaram.shape

# Save the MFCC features to a CSV file (optional)
flattened_df_nadaswaram.to_csv('/content/drive/MyDrive/mfcc_features_nadaswaram.csv', index=False)

print("MFCC features extracted and saved.")

"""##MFCC Extraction for Santoor"""

# Correct path to santoor folder
audio_folder_santoor = '/content/drive/MyDrive/Music-Samples/Santoor'
# Function to extract numbers from file names
def sort_key(filename):
    match = re.search(r'\d+', filename)
    return int(match.group()) if match else float('inf')

# List and sort files numerically
audio_files_santoor = sorted(os.listdir(audio_folder_santoor), key=sort_key)

# Display the sorted audio files
print(audio_files_santoor)

# Prepare a DataFrame to store the MFCCs
mfcc_features_santoor = []

# Iterate through each file in the folder
for file_name in audio_files_santoor:
    if file_name.endswith('.wav'):
        file_path = os.path.join(audio_folder_santoor, file_name)
        # Call preprocess_audio to load the audio and get the sample rate
        audio, sr = preprocess_audio(file_path, desired_length)

        mfcc_santoor = extract_mfcc(audio, sr)
        # Append a tuple of (MFCC features, label)
        mfcc_features_santoor.append((mfcc_santoor, 'Santoor'))

# Prepare a list to store the MFCC features and labels
mfcc_data_santoor = []

# Store each MFCC array and its label in the list
for mfcc_array_santoor, label in mfcc_features_santoor:
    mfcc_data_santoor.append({'features': mfcc_array_santoor, 'label': label})

# Convert to a DataFrame
mfcc_df_santoor = pd.DataFrame(mfcc_data_santoor)

# Flattening the features and storing them in a new DataFrame
flattened_features_santoor = []
labels_santoor = []

for index, row in mfcc_df_santoor.iterrows():
    # The features are already a numpy array, so no need to load with json.loads
    feature_array_santoor = row['features'].flatten()
    flattened_features_santoor.append(feature_array_santoor)
    labels_santoor.append(row['label'])

# Create a new DataFrame
flattened_df_santoor = pd.DataFrame(flattened_features_santoor)
flattened_df_santoor['label'] = labels_santoor

# Display the new DataFrame
flattened_df_santoor.shape

# Save the MFCC features to a CSV file (optional)
flattened_df_santoor.to_csv('/content/drive/MyDrive/mfcc_features_santoor.csv', index=False)

print("MFCC features extracted and saved.")

"""##MFCC Extraction for Shehnai

"""

# Correct path to Shehnai folder
audio_folder_shehnai = '/content/drive/MyDrive/Music-Samples/Shehnai'

# Function to extract numbers from file names
def sort_key(filename):
    match = re.search(r'\d+', filename)
    return int(match.group()) if match else float('inf')

# List and sort files numerically
audio_files_shehnai = sorted(os.listdir(audio_folder_shehnai), key=sort_key)

# Display the sorted audio files
print(audio_files_shehnai)

# Prepare a DataFrame to store the MFCCs
mfcc_features_shehnai = []

# Iterate through each file in the folder
for file_name in audio_files_shehnai:
    if file_name.endswith('.wav'):
        file_path = os.path.join(audio_folder_shehnai, file_name)
        # Call preprocess_audio to load the audio and get the sample rate
        audio, sr = preprocess_audio(file_path, desired_length)

        mfcc_shehnai = extract_mfcc(audio, sr)
        # Append a tuple of (MFCC features, label)
        mfcc_features_shehnai.append((mfcc_shehnai, 'Shehnai'))

# Prepare a list to store the MFCC features and labels
mfcc_data_shehnai = []

# Store each MFCC array and its label in the list
for mfcc_array_shehnai, label in mfcc_features_shehnai:
    mfcc_data_shehnai.append({'features': mfcc_array_shehnai, 'label': label})

# Convert to a DataFrame
mfcc_df_shehnai = pd.DataFrame(mfcc_data_shehnai)

# Flattening the features and storing them in a new DataFrame
flattened_features_shehnai = []
labels_shehnai = []

for index, row in mfcc_df_shehnai.iterrows():
    # The features are already a numpy array, so no need to load with json.loads
    feature_array_shehnai = row['features'].flatten()
    flattened_features_shehnai.append(feature_array_shehnai)
    labels_shehnai.append(row['label'])

# Create a new DataFrame
flattened_df_shehnai = pd.DataFrame(flattened_features_shehnai)
flattened_df_shehnai['label'] = labels_shehnai

# Display the new DataFrame
flattened_df_shehnai.shape

# Save the MFCC features to a CSV file (optional)
flattened_df_shehnai.to_csv('/content/drive/MyDrive/mfcc_features_shehnai.csv', index=False)

print("MFCC features extracted and saved.")

"""##MFCC Extraction for Thavil"""

# Correct path to Thavil folder
audio_folder_thavil = '/content/drive/MyDrive/Music-Samples/Thavil'

# Function to extract numbers from file names
def sort_key(filename):
    match = re.search(r'\d+', filename)
    return int(match.group()) if match else float('inf')

# List and sort files numerically
audio_files_thavil = sorted(os.listdir(audio_folder_thavil), key=sort_key)

# Display the sorted audio files
print(audio_files_thavil)

# Prepare a list to store the MFCCs
mfcc_features_thavil = []

# Iterate through each file in the folder
for file_name in audio_files_thavil:
    if file_name.endswith('.wav'):
        file_path = os.path.join(audio_folder_thavil, file_name)
        # Call preprocess_audio to load the audio and get the sample rate
        audio, sr = preprocess_audio(file_path, desired_length)

        mfcc_thavil = extract_mfcc(audio, sr)
        # Append a tuple of (MFCC features, label)
        mfcc_features_thavil.append((mfcc_thavil, 'Thavil'))

# Prepare a list to store the MFCC features and labels
mfcc_data_thavil = []

# Store each MFCC array and its label in the list
for mfcc_array_thavil, label in mfcc_features_thavil:
    mfcc_data_thavil.append({'features': mfcc_array_thavil, 'label': label})

# Convert to a DataFrame
mfcc_df_thavil = pd.DataFrame(mfcc_data_thavil)

# Flattening the features and storing them in a new DataFrame
flattened_features_thavil = []
labels_thavil = []

for index, row in mfcc_df_thavil.iterrows():
    feature_array_thavil = row['features'].flatten()
    flattened_features_thavil.append(feature_array_thavil)
    labels_thavil.append(row['label'])

# Create a new DataFrame
flattened_df_thavil = pd.DataFrame(flattened_features_thavil)
flattened_df_thavil['label'] = labels_thavil

# Display the new DataFrame shape
flattened_df_thavil.shape

# Save the MFCC features to a CSV file (optional)
flattened_df_thavil.to_csv('/content/drive/MyDrive/mfcc_features_thavil.csv', index=False)

print("MFCC features extracted and saved.")

"""##MFCC Extraction for Veena"""

# Correct path to Veena folder
audio_folder_veena = '/content/drive/MyDrive/Music-Samples/Veena'

# Function to extract numbers from file names
def sort_key(filename):
    match = re.search(r'\d+', filename)
    return int(match.group()) if match else float('inf')

# List and sort files numerically
audio_files_veena = sorted(os.listdir(audio_folder_veena), key=sort_key)

# Display the sorted audio files
print(audio_files_veena)

# Prepare a list to store the MFCCs
mfcc_features_veena = []

# Iterate through each file in the folder
for file_name in audio_files_veena:
    if file_name.endswith('.wav'):
        file_path = os.path.join(audio_folder_veena, file_name)
        # Call preprocess_audio to load the audio and get the sample rate
        audio, sr = preprocess_audio(file_path, desired_length)

        mfcc_veena = extract_mfcc(audio, sr)
        # Append a tuple of (MFCC features, label)
        mfcc_features_veena.append((mfcc_veena, 'Veena'))

# Prepare a list to store the MFCC features and labels
mfcc_data_veena = []

# Store each MFCC array and its label in the list
for mfcc_array_veena, label in mfcc_features_veena:
    mfcc_data_veena.append({'features': mfcc_array_veena, 'label': label})

# Convert to a DataFrame
mfcc_df_veena = pd.DataFrame(mfcc_data_veena)

# Flattening the features and storing them in a new DataFrame
flattened_features_veena = []
labels_veena = []

for index, row in mfcc_df_veena.iterrows():
    feature_array_veena = row['features'].flatten()
    flattened_features_veena.append(feature_array_veena)
    labels_veena.append(row['label'])

# Create a new DataFrame
flattened_df_veena = pd.DataFrame(flattened_features_veena)
flattened_df_veena['label'] = labels_veena

# Display the new DataFrame shape
flattened_df_veena.shape

# Save the MFCC features to a CSV file (optional)
flattened_df_veena.to_csv('/content/drive/MyDrive/mfcc_features_veena.csv', index=False)

print("MFCC features extracted and saved.")

"""##MFCC Extraction for Violin"""

# Correct path to Violin folder
audio_folder_violin = '/content/drive/MyDrive/Music-Samples/Violin'

# Function to extract numbers from file names
def sort_key(filename):
    match = re.search(r'\d+', filename)
    return int(match.group()) if match else float('inf')

# List and sort files numerically
audio_files_violin = sorted(os.listdir(audio_folder_violin), key=sort_key)

# Display the sorted audio files
print(audio_files_violin)

# Prepare a list to store the MFCCs
mfcc_features_violin = []

# Iterate through each file in the folder
for file_name in audio_files_violin:
    if file_name.endswith('.wav'):
        file_path = os.path.join(audio_folder_violin, file_name)
        # Call preprocess_audio to load the audio and get the sample rate
        audio, sr = preprocess_audio(file_path, desired_length)

        mfcc_violin = extract_mfcc(audio, sr)
        # Append a tuple of (MFCC features, label)
        mfcc_features_violin.append((mfcc_violin, 'Violin'))

# Prepare a list to store the MFCC features and labels
mfcc_data_violin = []

# Store each MFCC array and its label in the list
for mfcc_array_violin, label in mfcc_features_violin:
    mfcc_data_violin.append({'features': mfcc_array_violin, 'label': label})

# Convert to a DataFrame
mfcc_df_violin = pd.DataFrame(mfcc_data_violin)

# Flattening the features and storing them in a new DataFrame
flattened_features_violin = []
labels_violin = []

for index, row in mfcc_df_violin.iterrows():
    feature_array_violin = row['features'].flatten()
    flattened_features_violin.append(feature_array_violin)
    labels_violin.append(row['label'])

# Create a new DataFrame
flattened_df_violin = pd.DataFrame(flattened_features_violin)
flattened_df_violin['label'] = labels_violin

# Display the new DataFrame shape
flattened_df_violin.shape

# Save the MFCC features to a CSV file (optional)
flattened_df_violin.to_csv('/content/drive/MyDrive/mfcc_features_violin.csv', index=False)

print("MFCC features extracted and saved.")

"""##Combining all datasets together into Single DataFrame"""

# List of DataFrames to combine (ONLY Indian instruments)
dataframes = [
    flattened_df_flute,
    flattened_df_nadaswaram,
    flattened_df_shehnai,
    flattened_df_thavil,
    flattened_df_mridangam,
    flattened_df_santoor,
    flattened_df_veena,
    flattened_df_violin
]

# Combine all DataFrames into one
combined_df = pd.concat(dataframes, ignore_index=True)

# Save the MFCC features to a CSV file
combined_df.to_csv('/content/drive/MyDrive/MFCC_Features_Indian_Instruments.csv', index=False)

print("MFCC features extracted and saved.")

combined_df.shape