# -*- coding: utf-8 -*-
"""Copy of Final_Year_Project_UNET.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wHlgNXmzgzuctng7KEgfSZe0-claEPdx
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import numpy as np
import random
import tensorflow as tf

from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, Conv2D, MaxPooling2D,
    Flatten, Dense, Dropout
)
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing.image import load_img, img_to_array
from tensorflow.keras.utils import to_categorical

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

seed = 42
os.environ['PYTHONHASHSEED'] = str(seed)
random.seed(seed)
np.random.seed(seed)
tf.random.set_seed(seed)

DATASET_PATH = '/content/drive/MyDrive/STFT_Spectrograms'

IMG_HEIGHT = 128
IMG_WIDTH = 128
CHANNELS = 1

X = []
y = []

for instrument in sorted(os.listdir(DATASET_PATH)):
    instrument_path = os.path.join(DATASET_PATH, instrument)
    if not os.path.isdir(instrument_path):
        continue

    for img_name in os.listdir(instrument_path):
        if img_name.endswith('.png'):
            img_path = os.path.join(instrument_path, img_name)

            img = load_img(
                img_path,
                color_mode='grayscale',
                target_size=(IMG_HEIGHT, IMG_WIDTH)
            )

            img_array = img_to_array(img) / 255.0
            X.append(img_array)
            y.append(instrument)

X = np.array(X)
y = np.array(y)

print("X shape:", X.shape)
print("y shape:", y.shape)

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
y_categorical = to_categorical(y_encoded)

print("Classes:", label_encoder.classes_)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_categorical,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

inputs = Input((IMG_HEIGHT, IMG_WIDTH, CHANNELS))

# Encoder
c1 = Conv2D(32, (3,3), activation='relu', padding='same')(inputs)
p1 = MaxPooling2D((2,2))(c1)

c2 = Conv2D(64, (3,3), activation='relu', padding='same')(p1)
p2 = MaxPooling2D((2,2))(c2)

c3 = Conv2D(128, (3,3), activation='relu', padding='same')(p2)
p3 = MaxPooling2D((2,2))(c3)

# Bottleneck (CLASS-AWARE)
bottleneck = Conv2D(256, (3,3), activation='relu', padding='same')(p3)

from tensorflow.keras.layers import BatchNormalization

x = Flatten()(bottleneck)
x = Dense(128, activation='relu')(x)
x = BatchNormalization()(x)
x = Dropout(0.5)(x)

outputs = Dense(y_train.shape[1], activation='softmax')(x)

model = Model(inputs, outputs)

model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

model.fit(
    X_train, y_train,
    epochs=25,
    batch_size=16,
    validation_split=0.1,
    shuffle=True
)

loss, acc = model.evaluate(X_test, y_test, verbose=1)
print(f"U-Net Encoder + Classifier Accuracy: {acc * 100:.2f}%")

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# Predict class probabilities
y_pred_probs = model.predict(X_test)

# Convert probabilities → class labels
y_pred = np.argmax(y_pred_probs, axis=1)
y_true = np.argmax(y_test, axis=1)

# Print classification report
print(classification_report(y_true, y_pred, target_names=label_encoder.classes_))

import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='YlGnBu',
    cbar=True,
    linewidths=0.8,
    linecolor='white',
    square=True,
    xticklabels=label_encoder.classes_,
    yticklabels=label_encoder.classes_,
    annot_kws={"size": 11, "weight": "bold"}
)

plt.xlabel("Predicted Label", fontsize=12, fontweight='bold')
plt.ylabel("True Label", fontsize=12, fontweight='bold')
plt.title("Confusion Matrix (UNET)", fontsize=14, fontweight='bold', pad=12)
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(rotation=0, fontsize=10)
plt.tight_layout()
plt.show()

plt.savefig("unet_confusion_matrix.png", dpi=300, bbox_inches='tight')

from sklearn.model_selection import KFold
from tensorflow.keras.models import Model
import numpy as np

kfold = KFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = []

for fold, (train_idx, val_idx) in enumerate(kfold.split(X, y_categorical)):
    print(f"\n===== Fold {fold+1} =====")

    X_train_cv, X_val_cv = X[train_idx], X[val_idx]
    y_train_cv, y_val_cv = y_categorical[train_idx], y_categorical[val_idx]

    # Rebuild model for each fold
    inputs = Input((IMG_HEIGHT, IMG_WIDTH, CHANNELS))

    c1 = Conv2D(32, (3,3), activation='relu', padding='same')(inputs)
    p1 = MaxPooling2D((2,2))(c1)

    c2 = Conv2D(64, (3,3), activation='relu', padding='same')(p1)
    p2 = MaxPooling2D((2,2))(c2)

    c3 = Conv2D(128, (3,3), activation='relu', padding='same')(p2)
    p3 = MaxPooling2D((2,2))(c3)

    bottleneck = Conv2D(256, (3,3), activation='relu', padding='same')(p3)

    x = Flatten()(bottleneck)
    x = Dense(128, activation='relu')(x)
    x = Dropout(0.5)(x)
    outputs = Dense(y_train_cv.shape[1], activation='softmax')(x)

    model = Model(inputs, outputs)

    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

    model.fit(X_train_cv, y_train_cv, epochs=10, batch_size=16, verbose=0)

    loss, acc = model.evaluate(X_val_cv, y_val_cv, verbose=0)
    print(f"Fold Accuracy: {acc*100:.2f}%")
    cv_scores.append(acc)

print("\nMean CV Accuracy:", np.mean(cv_scores)*100)
print("Std Dev:", np.std(cv_scores)*100)