# -*- coding: utf-8 -*-
"""Copy of Final_Year_Project_ML_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AleSmfzwUI67835fcm0q0bDRDiiUHrVK

#First Phase - II (ML Models)

##Data Loading
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Basic imports for ML
import pandas as pd
import numpy as np

# Path to the combined MFCC dataset
DATASET_PATH = '/content/drive/MyDrive/MFCC_Features_Indian_Instruments.csv'

# Load the dataset
df = pd.read_csv(DATASET_PATH)

# Display basic information
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns)

# Display first few rows
df.head()

"""##EDA"""

# Separate features and labels
X = df.drop('label', axis=1)
y = df['label']

print("Features shape (X):", X.shape)
print("Labels shape (y):", y.shape)

print("\nUnique labels:")
print(y.unique())

from sklearn.preprocessing import LabelEncoder

# Initialize label encoder
label_encoder = LabelEncoder()

# Encode labels
y_encoded = label_encoder.fit_transform(y)

print("\nLabel mapping:")

for label, encoded in zip(label_encoder.classes_, range(len(label_encoder.classes_))):
    print(f"{label} -> {encoded}")

from sklearn.model_selection import train_test_split

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print("Training features shape:", X_train.shape)
print("Testing features shape:", X_test.shape)
print("Training labels shape:", y_train.shape)
print("Testing labels shape:", y_test.shape)

from sklearn.preprocessing import StandardScaler

# Initialize scaler
scaler = StandardScaler()

# Fit ONLY on training data
X_train_scaled = scaler.fit_transform(X_train)

# Transform test data using same scaler
X_test_scaled = scaler.transform(X_test)

print("Scaled training features shape:", X_train_scaled.shape)
print("Scaled testing features shape:", X_test_scaled.shape)

"""##Machine Learning Models"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# Initialize Logistic Regression model
log_reg = LogisticRegression(
    max_iter=1000,
    random_state=42
)

# Train the model
log_reg.fit(X_train_scaled, y_train)

# Predict on test data
y_pred_lr = log_reg.predict(X_test_scaled)

# Evaluate performance
lr_accuracy = accuracy_score(y_test, y_pred_lr)

print("Logistic Regression Accuracy:", lr_accuracy)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_lr, target_names=label_encoder.classes_))

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

# Initialize KNN (start with k=5)
knn = KNeighborsClassifier(n_neighbors=5)

# Train KNN
knn.fit(X_train_scaled, y_train)

# Predict on test data
y_pred_knn = knn.predict(X_test_scaled)

# Evaluate performance
knn_accuracy = accuracy_score(y_test, y_pred_knn)

print("KNN Accuracy:", knn_accuracy)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_knn, target_names=label_encoder.classes_))

from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

# Initialize Linear SVM
svm_model = LinearSVC(random_state=42, max_iter=5000)

# Train SVM
svm_model.fit(X_train_scaled, y_train)

# Predict on test data
y_pred_svm = svm_model.predict(X_test_scaled)

# Evaluate performance
svm_accuracy = accuracy_score(y_test, y_pred_svm)

print("SVM Accuracy:", svm_accuracy)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_svm, target_names=label_encoder.classes_))

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# Initialize Random Forest
rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

# Train the model
rf_model.fit(X_train_scaled, y_train)

# Predict on test data
y_pred_rf = rf_model.predict(X_test_scaled)

# Evaluate performance
rf_accuracy = accuracy_score(y_test, y_pred_rf)

print("Random Forest Accuracy:", rf_accuracy)
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_rf, target_names=label_encoder.classes_))

from sklearn.model_selection import cross_val_score

# Define models
models = {
    "Logistic Regression": log_reg,
    "SVM": svm_model,
    "Random Forest": rf_model,
    "KNN": knn
}

# Compute 5-fold CV accuracy
for name, model in models.items():
    scores = cross_val_score(model, X, y_encoded, cv=5, scoring='accuracy')
    print(f"{name} CV Accuracy: {scores.mean():.4f}")

"""##Important Diagrams"""

import matplotlib.pyplot as plt

models = ['Logistic Regression', 'KNN', 'SVM', 'Random Forest']
accuracies = [
    accuracy_score(y_test, y_pred_lr),
    accuracy_score(y_test, y_pred_knn),
    accuracy_score(y_test, y_pred_svm),
    accuracy_score(y_test, y_pred_rf)
]

plt.figure()
plt.bar(models, accuracies)
plt.title("Model Comparison")
plt.ylabel("Accuracy")
plt.xticks(rotation=20)
plt.tight_layout()
plt.savefig("model_comparison.png", dpi=300)
plt.show()

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred_rf)

plt.figure(figsize=(7, 6))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='YlGnBu',
    cbar=True,
    linewidths=0.8,
    linecolor='white',
    square=True,
    xticklabels=label_encoder.classes_,
    yticklabels=label_encoder.classes_,
    annot_kws={"size": 11, "weight": "bold"}
)

plt.title("Confusion Matrix - Random Forest", fontsize=14, fontweight='bold', pad=12)
plt.xlabel("Predicted Label", fontsize=12, fontweight='bold')
plt.ylabel("True Label", fontsize=12, fontweight='bold')
plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(rotation=0, fontsize=10)

plt.tight_layout()
plt.savefig("rf_confusion_matrix.png", dpi=300, bbox_inches='tight')
plt.show()

"""##Saving the model For Deployment"""

import joblib

# Save Random Forest model
joblib.dump(rf_model, "random_forest_model.pkl")

print("Random Forest saved!")

joblib.dump(label_encoder, "label_encoder.pkl")
print("Label encoder saved!")

joblib.dump(scaler, "scaler.pkl")
print("Scaler saved!")